from spr import *

#CHILDS OF PERSON
class Prof ( Person ) : ...

class Student ( Person ) : ...


#CHILDS OF BUILDING
class Lab (Building) : ...

class Lecture_hall (Building) : ...
    

#CHILDS OF SPECIALITY
class Mech (Speciality) : ...

class Elec (Speciality) : ...
